(() => {
 const dialog=document.getElementById('accountDialog'),title=document.getElementById('accountTitle'),message=document.getElementById('accountMessage'),invite=document.getElementById('inviteForm'),profile=document.getElementById('accountSuccess');let user=null,returnFocus;
 async function request(body){const response=await fetch('/api/account',{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});const data=await response.json();if(response.status===401){location.replace('/?next='+encodeURIComponent('/app'+location.hash));throw Error('Your session expired. Please log in again.');}if(!response.ok)throw Error(data.error||'Please try again shortly.');return data;}
 function renderUser(value){user=value;if(!user){location.replace('/?next='+encodeURIComponent('/app'+location.hash));return;}document.getElementById('profileLabel').textContent='Account';document.getElementById('profileAvatar').textContent=user.email[0].toUpperCase();document.getElementById('profileButton').setAttribute('aria-label','Signed in as '+user.email+'. View account');document.getElementById('profileButton').title=user.email;document.getElementById('inviteCustomers').hidden=!user.canInvite;}
 function open(isInvite){if(!user)return;returnFocus=document.activeElement;invite.hidden=!isInvite;profile.hidden=isInvite;title.textContent=isInvite?'Invite a customer':'Your account';profile.querySelector('p').textContent='Signed in as '+user.email+'.';message.textContent='';dialog.showModal();(isInvite?document.getElementById('customerEmail'):title).focus();}
 document.getElementById('profileButton').addEventListener('click',()=>open(false));document.getElementById('inviteCustomers').addEventListener('click',()=>open(true));
 invite.addEventListener('submit',async event=>{event.preventDefault();const b=invite.querySelector('button');b.disabled=true;message.textContent='';try{const result=await request({action:'invite',email:document.getElementById('customerEmail').value.trim()});if(!result.sent)throw Error('Invitation could not be confirmed.');invite.hidden=true;profile.hidden=false;title.textContent='Invitation sent';profile.querySelector('p').textContent='Your customer will receive an email inviting them to join Turnli.';title.focus();invite.reset();}catch(error){message.textContent=error.message;}finally{b.disabled=false;}});
 async function signOut(event){const b=event.currentTarget;b.disabled=true;try{await request({action:'logout'});try{localStorage.setItem('turnli-signout',String(Date.now()));}catch{}document.body.classList.add('session-checking');location.replace('/');}catch(error){if(!dialog.open)open(false);message.textContent=error.message;b.disabled=false;}}
 document.getElementById('signOutButton').addEventListener('click',signOut);
 dialog.addEventListener('close',()=>{if(returnFocus?.isConnected&&!returnFocus.closest('.hidden'))returnFocus.focus();});
 request().then(data=>renderUser(data.user)).catch(()=>location.replace('/?next='+encodeURIComponent('/app'+location.hash)));
})();
