(() => {
 const $=id=>document.getElementById(id), select=$('workspaceProperty'),status=$('workspaceStatus');
 if(!select)return;
 let state={revision:0,data:{properties:[]}},selected='',kind='regular',editingProperty='',busy=false,ready=false;
 const labels={regular:'Regular Clean List',deep:'Deep Clean List',faqs:'FAQs'};
 const property=()=>state.data.properties.find(p=>p.id===selected);
 const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
 async function request(body){const r=await fetch('/api/dashboard',{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify({...body,revision:state.revision}):undefined});if(r.status===401){location.replace('/');throw Error('Please log in.');}const data=await r.json();if(!r.ok){if(r.status===409)$('reloadWorkspace').hidden=false;throw Error(data.error||'Please try again.');}return data;}
 function render(){select.replaceChildren(node('option','Choose a property'));select.firstChild.value='';for(const p of state.data.properties){const o=node('option',p.name);o.value=p.id;select.append(o);}if(!property())selected=state.data.properties[0]?.id||'';select.value=selected;const p=property();$('editProperty').disabled=!p||busy;$('newProperty').disabled=!ready||busy;$('propertySummary').textContent=p?p.notes||'Your property’s cleaning tools are saved to this workspace.':'Add your property, then set up its checklists and FAQs.';for(const b of document.querySelectorAll('[data-workspace]')){const k=b.dataset.workspace;const label=b.querySelector('.nav-label');const title=(p?.[k].length||typeof openChecklist==='function'?'':'＋ ')+labels[k];if(label)label.textContent=title;else b.textContent=title;b.disabled=!ready||busy;}}
 async function load(){ready=false;render();status.textContent='Loading your cleaning tools…';try{state=await request();ready=true;render();status.textContent='';$('reloadWorkspace').hidden=true;}catch(e){status.textContent=e.message;$('reloadWorkspace').hidden=false;}}
 async function save(body,message){if(busy)return false;busy=true;render();try{state=await request(body);status.textContent='Saved to your workspace.';if(message)message.textContent='Saved.';return true;}catch(e){status.textContent=e.message;if(message)message.textContent=e.message;return false;}finally{busy=false;render();}}
 function openDialog(d){d._returnFocus=document.activeElement;d.showModal();(d.querySelector('h2')||d).setAttribute('tabindex','-1');d.querySelector('h2')?.focus();}
 for(const d of [$('propertyDialog'),$('workspaceContentDialog'),$('workspaceIssueDialog')]){d.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>d.close()));d.addEventListener('close',()=>{d._returnFocus?.focus();if(d.id==='workspaceContentDialog'){if(!d._historyClosing&&location.hash.startsWith('#tools-'))history.back();d._historyClosing=false;}});}
 function setup(p){editingProperty=p?.id||'';$('setupName').value=p?.name||'';$('setupPhone').value=p?.phone||'';$('setupNotes').value=p?.notes||'';$('propertyDialog').querySelector('[data-dialog-status]').textContent='';openDialog($('propertyDialog'));$('setupName').focus();}
 $('newProperty').addEventListener('click',()=>setup());$('editProperty').addEventListener('click',()=>setup(property()));select.addEventListener('change',()=>{selected=select.value;render();});$('reloadWorkspace').addEventListener('click',load);
 $('propertySetupForm').addEventListener('submit',async e=>{e.preventDefault();const ok=await save({action:'property',id:editingProperty,name:$('setupName').value,phone:$('setupPhone').value,notes:$('setupNotes').value},$('propertyDialog').querySelector('[data-dialog-status]'));if(ok){selected=editingProperty||state.data.properties.at(-1).id;render();$('propertyDialog').close();}});
 function faqRow(q={question:'',answer:''}){const row=node('div',undefined,'workspace-faq-row');for(const [key,label,max] of [['question','Question',300],['answer','Answer',3000]]){const l=node('label',label,'field'),input=node('textarea');input.value=q[key];input.required=true;input.maxLength=max;input.rows=key==='question'?2:4;input.dataset.field=key;l.append(input);row.append(l);}const remove=node('button','Remove question','back');remove.type='button';remove.addEventListener('click',()=>{row.remove();$('addFAQRow').focus();});row.append(remove);$('workspaceFAQFields').append(row);}
 function editContent(){const p=property();$('workspaceContentView').hidden=true;$('workspaceContentActions').hidden=true;$('workspaceContentForm').hidden=false;$('workspaceTaskField').hidden=kind==='faqs';$('workspaceEditNote').hidden=kind==='faqs';$('workspaceFAQFields').hidden=kind!=='faqs';$('addFAQRow').hidden=kind!=='faqs';$('workspaceContentForm').querySelector('[data-dialog-status]').textContent='';$('workspaceTaskLines').value=kind==='faqs'?'':p[kind].join('\n');$('workspaceFAQFields').replaceChildren();if(kind==='faqs')(p.faqs.length?p.faqs:[{question:'',answer:''}]).forEach(faqRow);$('workspaceContentForm').querySelector(kind==='faqs'?'textarea[data-field=question]':'#workspaceTaskLines')?.focus();}
 function content(){const p=property(),view=$('workspaceContentView');view.hidden=false;view.replaceChildren();$('workspaceContentForm').hidden=true;$('workspaceContentActions').hidden=false;$('workspaceContentTitle').textContent=labels[kind];$('workspaceContentProperty').textContent=p.name;$('workspaceContentStatus').textContent='';$('resetWorkspaceChecklist').hidden=kind==='faqs';$('reportWorkspaceIssue').hidden=kind==='faqs'||!p.phone;
 if(kind==='faqs'){for(const f of p.faqs){const d=node('details');d.append(node('summary',f.question),node('p',f.answer));view.append(d);}}else{const progress=node('p',`${p.checked[kind].length} of ${p[kind].length} completed`);progress.setAttribute('role','status');view.append(progress);p[kind].forEach((task,index)=>{const l=node('label'),box=node('input');box.type='checkbox';box.checked=p.checked[kind].includes(index);l.append(box,node('span',task));view.append(l);box.addEventListener('change',async()=>{const checked=box.checked;view.querySelectorAll('input').forEach(i=>i.disabled=true);const ok=await save({action:'check',id:p.id,kind,index,checked},$('workspaceContentStatus'));if(!ok)box.checked=!checked;progress.textContent=`${property().checked[kind].length} of ${property()[kind].length} completed`;view.querySelectorAll('input').forEach(i=>i.disabled=false);});});}if(!p[kind].length)view.append(node('p','Nothing added yet. Choose Edit to set this up.'));
 }
 function openContent(k,push=true){if(!property()&&typeof openChecklist==='function'){k==='faqs'?openFAQ():openChecklist(k);return;}if(!property()){status.textContent='Add a property first to save its cleaning tools.';setup();return;}kind=k;content();if(push)history.pushState({turnliTools:true},'',location.pathname+location.search+'#tools-'+kind);openDialog($('workspaceContentDialog'));if(!property()[kind].length)editContent();}
 document.querySelectorAll('[data-workspace]').forEach(b=>b.addEventListener('click',()=>openContent(b.dataset.workspace)));
 $('editWorkspaceContent').addEventListener('click',editContent);$('addFAQRow').addEventListener('click',()=>faqRow());
 $('workspaceContentForm').addEventListener('submit',async e=>{e.preventDefault();const items=kind==='faqs'?[...$('workspaceFAQFields').children].map(row=>({question:row.querySelector('[data-field=question]').value,answer:row.querySelector('[data-field=answer]').value})):$('workspaceTaskLines').value.split('\n').map(s=>s.trim()).filter(Boolean);if(await save({action:'content',id:selected,kind,items},$('workspaceContentForm').querySelector('[data-dialog-status]'))){content();$('workspaceContentStatus').textContent='Saved to your workspace.';}});
 $('resetWorkspaceChecklist').addEventListener('click',async()=>{if(confirm('Start a new clean? This clears completion ticks but keeps all checklist items.'))if(await save({action:'reset',id:selected,kind},$('workspaceContentStatus')))content();});
 function issueLink(){const p=property();$('workspaceIssueLink').href='https://wa.me/'+p.phone.replace(/\D/g,'')+'?text='+encodeURIComponent(`Hi, I need to report ${$('workspaceIssueType').value.toLowerCase()} at ${p.name} during the ${kind==='deep'?'deep':'regular'} clean on ${new Date().toLocaleDateString('en-GB')}. Details: `);}
 $('reportWorkspaceIssue').addEventListener('click',()=>{issueLink();openDialog($('workspaceIssueDialog'));});$('workspaceIssueType').addEventListener('change',issueLink);
 window.addEventListener('popstate',()=>{const k=location.hash.replace('#tools-','');if(['regular','deep','faqs'].includes(k)&&location.hash.startsWith('#tools-')&&property()){if($('workspaceContentDialog').open){$('workspaceContentDialog')._historyClosing=true;$('workspaceContentDialog').close();}openContent(k,false);}else{if($('workspaceIssueDialog').open)$('workspaceIssueDialog').close();if($('workspaceContentDialog').open){$('workspaceContentDialog')._historyClosing=true;$('workspaceContentDialog').close();}}});
 const reminder=$('workspaceReminder');if(reminder){const reminders=['Always check the calendar for your next clean. Don’t rely on WhatsApp notifications.','Use the property checklist during every clean. Your progress is saved to your workspace.','Report damage, missing items or maintenance issues to the host as soon as possible.'];let index=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches;const toggle=$('workspaceReminderToggle'),label=()=>toggle.textContent=paused?'Resume reminders':'Pause reminders';label();toggle.addEventListener('click',()=>{paused=!paused;label();});setInterval(()=>{if(!paused&&!document.hidden){index=(index+1)%reminders.length;reminder.textContent=reminders[index];}},10000);}
 document.addEventListener('turnli:calendars',event=>{const empty=!event.detail.calendars.length;const button=$('manageCalendars');button.textContent=empty?'＋ Add Calendar':'Manage calendars';button.dataset.empty=String(empty);});
 $('manageCalendars').addEventListener('click',()=>{if($('manageCalendars').dataset.empty==='true')setTimeout(()=>$('addCalendar').click(),0);});
 load();
})();
