(() => {
 const home=document.getElementById('homeView'),wrap=home.closest('.wrap'),tools=document.getElementById('workspaceTools');if(!tools)return;
 document.body.classList.add('workspace-shell');
 const header=home.querySelector('.brand-header');wrap.prepend(header);
 const frame=document.createElement('div');frame.className='workspace-frame';const aside=document.createElement('aside');aside.className='app-sidebar';aside.setAttribute('aria-label','Workspace navigation');const content=document.createElement('div');content.className='workspace-main';
 for(const main of [...wrap.querySelectorAll(':scope > main')])content.append(main);frame.append(aside,content);wrap.append(frame);
 const paths={calendar:'M4 5h16v16H4z M8 2v6 M16 2v6 M4 10h16',regular:'M9 6h12 M9 12h12 M9 18h12 M2 6l2 2 3-4 M2 12l2 2 3-4 M2 18l2 2 3-4',deep:'M5 3h14v18H5z M9 8h6 M9 12h6 M9 16h6',faqs:'M12 17h.01 M9 8a3 3 0 0 1 6 0c0 2-3 2-3 5 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',copy:'M8 8h13v13H8z M16 8V3H3v13h5',add:'M12 4v16 M4 12h16',collapse:'M14 6l-6 6 6 6',more:'M5 12h.01 M12 12h.01 M19 12h.01'};
 function icon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.innerHTML=`<path d="${paths[name]}" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>`;return svg;}
 function decorate(button,name,label){button.className='nav-item';button.title=label;button.setAttribute('aria-label',label);const text=document.createElement('span');text.className='nav-label';text.textContent=label;button.replaceChildren(icon(name),text);return button;}
 const collapse=document.createElement('button');collapse.type='button';collapse.id='collapseSidebar';collapse.className='collapse-sidebar';collapse.title='Collapse sidebar';collapse.setAttribute('aria-label','Collapse sidebar');collapse.setAttribute('aria-expanded','true');collapse.append(icon('collapse'));aside.append(collapse);
 const nav=document.createElement('nav');nav.className='primary-navigation';nav.setAttribute('aria-label','Main destinations');aside.append(nav);
 const calendar=decorate(document.createElement('button'),'calendar','Calendar');calendar.type='button';calendar.dataset.destination='calendar';nav.append(calendar);
 function heading(text){const p=document.createElement('p');p.className='nav-group-label';p.textContent=text;return p;}
 nav.append(heading('Cleaning'));
 for(const [key,label] of [['regular','Regular Clean List'],['deep','Deep Clean List'],['faqs','FAQs']]){if(key==='faqs')nav.append(heading('Support'));const button=tools.querySelector(`[data-workspace=${key}]`);decorate(button,key,label);button.dataset.destination=key;nav.append(button);}
 const secondary=document.createElement('div');secondary.className='sidebar-secondary';secondary.append(heading('Calendar tools'));
 for(const [id,key,label] of [['subscribeCalendar','add','Add to Calendar'],['copyCalendar','copy','Copy iCal Link']]){const b=document.getElementById(id);decorate(b,key,label);if(id==='copyCalendar')b.querySelector('.nav-label').dataset.copyLabel='';secondary.append(b);}
 const context=tools.querySelector('.workspace-property');secondary.append(heading('Property setup'),context);
 secondary.append(document.getElementById('workspaceStatus'),document.getElementById('reloadWorkspace'));
 const reminder=home.querySelector('.hero');if(reminder){const details=document.createElement('details');details.className='sidebar-reminder';const summary=document.createElement('summary');summary.textContent='Cleaner reminder';details.append(summary,reminder);secondary.append(details);}
 aside.append(secondary);tools.remove();home.querySelector('.quick-actions')?.remove();home.querySelector('#actionsHeading')?.remove();
 const mainView=document.getElementById('workspaceContentDialog');content.append(mainView);mainView.showModal=()=>{mainView.hidden=false;mainView.open=true;for(const m of content.querySelectorAll(':scope > main'))m.classList.add('hidden');updateActive();};mainView.close=()=>{mainView.hidden=true;mainView.open=false;home.classList.remove('hidden');mainView.dispatchEvent(new Event('close'));updateActive();};
 function updateActive(){const hash=location.hash;const current=hash.includes('regular')?'regular':hash.includes('deep')?'deep':hash.includes('faq')?'faqs':'calendar';for(const b of nav.querySelectorAll('[data-destination]')){b.classList.toggle('active',b.dataset.destination===current);if(b.dataset.destination===current)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}}
 calendar.addEventListener('click',()=>{if(mainView.open){mainView._historyClosing=true;mainView.close();}if(typeof goHome==='function')goHome(false,false);history.pushState({},'',location.pathname+location.search);home.classList.remove('hidden');updateActive();document.getElementById('cleaningCalendar').focus();});
 nav.addEventListener('click',()=>setTimeout(updateActive,0));window.addEventListener('popstate',updateActive);updateActive();
 const prefStatus=document.createElement('p');prefStatus.className='sidebar-pref-status';prefStatus.setAttribute('role','status');secondary.append(prefStatus);let changed=false;
 function collapsed(value){document.body.classList.toggle('sidebar-collapsed',value);collapse.setAttribute('aria-expanded',String(!value));collapse.title=value?'Expand sidebar':'Collapse sidebar';collapse.setAttribute('aria-label',collapse.title);}
 fetch('/api/dashboard?action=preferences',{cache:'no-store',credentials:'same-origin'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(p=>{if(!changed)collapsed(p.sidebarCollapsed===true);}).catch(()=>{});
 collapse.addEventListener('click',async()=>{changed=true;const value=!document.body.classList.contains('sidebar-collapsed');collapsed(value);collapse.disabled=true;try{const r=await fetch('/api/dashboard',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'preferences',sidebarCollapsed:value})});if(!r.ok)throw Error();prefStatus.textContent='';}catch{collapsed(!value);prefStatus.textContent='Sidebar preference wasn’t saved. Please try again.';}finally{collapse.disabled=false;}});
 const sheet=document.createElement('dialog');sheet.id='mobileToolsDialog';sheet.setAttribute('aria-labelledby','mobileToolsTitle');sheet.innerHTML='<h2 id="mobileToolsTitle">Workspace tools</h2><button type="button" class="back" id="closeMobileTools">Close</button>';document.body.append(sheet);
 const more=decorate(document.createElement('button'),'more','More');more.type='button';more.classList.add('mobile-more');header.append(more);more.addEventListener('click',()=>sheet.showModal());sheet.querySelector('button').addEventListener('click',()=>sheet.close());sheet.addEventListener('close',()=>more.focus());
 const media=matchMedia('(max-width:700px)');function responsive(){if(sheet.open)sheet.close();if(media.matches){document.body.append(nav);sheet.append(secondary);}else{aside.insertBefore(nav,collapse.nextSibling);aside.append(secondary);}}media.addEventListener('change',responsive);responsive();
})();
