const {test}=require('node:test');const assert=require('node:assert/strict');const {createHandler,OWNER_EMAIL}=require('../lib/account.cjs');
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v},status(s){this.code=s;return this},json(data){this.data=data;return this}};}
function request(body,session=true){return {method:'POST',headers:{origin:'https://turnli.vercel.app','content-type':'application/json',cookie:session?'__Host-turnly-session=valid':''},body};}
function sdk(owner=true){return {validateSession:async token=>{if(token!=='valid')throw Error('invalid')},me:async()=>({ok:true,data:{email:owner?OWNER_EMAIL:'customer@example.com',verifiedEmail:true}}),management:{user:{invite:async()=>({ok:true})}}};}
test('anonymous invitations are rejected before email sending',async()=>{const service=sdk();service.management.user.invite=()=>assert.fail('must not send');const res=response();await createHandler(()=>service)(request({action:'invite',email:'customer@example.com'},false),res);assert.equal(res.code,401);});
test('customers cannot invite other customers',async()=>{const res=response();await createHandler(()=>sdk(false))(request({action:'invite',email:'customer@example.com'}),res);assert.equal(res.code,403);});
test('unverified owner email cannot invite',async()=>{const service=sdk();service.me=async()=>({ok:true,data:{email:OWNER_EMAIL,verifiedEmail:false}});const res=response();await createHandler(()=>service)(request({action:'invite',email:'customer@example.com'}),res);assert.equal(res.code,403);});
test('cross-origin sends are rejected',async()=>{const req=request({action:'invite',email:'customer@example.com'});req.headers.origin='https://evil.example';const res=response();await createHandler(()=>{assert.fail('must not call provider')})(req,res);assert.equal(res.code,403);});
test('configuration missing and provider failures never report sent',async()=>{const old=process.env.DESCOPE_MANAGEMENT_KEY;try{delete process.env.DESCOPE_MANAGEMENT_KEY;const res=response();await createHandler(()=>sdk())(request({action:'invite',email:'customer@example.com'}),res);assert.equal(res.code,503);assert(!res.data.sent);process.env.DESCOPE_MANAGEMENT_KEY='unit-test-only';const service=sdk();service.management.user.invite=async()=>({ok:false,code:500});const bad=response();await createHandler(()=>service)(request({action:'invite',email:'customer@example.com'}),bad);assert(!bad.data.sent);}finally{if(old===undefined)delete process.env.DESCOPE_MANAGEMENT_KEY;else process.env.DESCOPE_MANAGEMENT_KEY=old;}});
test('authorized invite uses the fixed join link and no elevated roles',async()=>{const old=process.env.DESCOPE_MANAGEMENT_KEY;process.env.DESCOPE_MANAGEMENT_KEY='unit-test-only';try{const service=sdk();service.management.user.invite=async(email,options)=>{assert.equal(email,'customer@example.com');assert.equal(options.inviteUrl,'https://turnli.vercel.app/?join=1');assert.equal(options.sendMail,true);assert.equal(options.sendSMS,false);assert.equal(options.roles,undefined);return {ok:true}};const res=response();await createHandler(()=>service)(request({action:'invite',email:'Customer@example.com'}),res);assert.deepEqual(res.data,{sent:true});}finally{if(old===undefined)delete process.env.DESCOPE_MANAGEMENT_KEY;else process.env.DESCOPE_MANAGEMENT_KEY=old;}});
test('non-owner sign-in never self-registers',async()=>{const service=sdk();service.otp={signIn:{email:async()=>({ok:false,code:400})},signUpOrIn:{email:()=>assert.fail('must not register')}};const res=response();await createHandler(()=>service)(request({action:'send-code',email:'stranger@example.com'},false),res);assert.equal(res.code,400);});
test('OTP verification uses secure HttpOnly session cookies without returning tokens',async()=>{const service=sdk();service.otp={verify:{email:async()=>({ok:true,data:{sessionJwt:'session',refreshJwt:'refresh'}})}};const res=response();await createHandler(()=>service)(request({action:'verify-code',email:OWNER_EMAIL,code:'123456'},false),res);assert.equal(res.code,200);assert(res.headers['Set-Cookie'].every(v=>v.includes('HttpOnly; Secure; SameSite=Lax')));assert(!JSON.stringify(res.data).includes('session'));});
test('real SDK initializes with project config and handles a signed-out visitor',async()=>{const old=process.env.DESCOPE_PROJECT_ID;process.env.DESCOPE_PROJECT_ID='P2test';try{const res=response();await createHandler()({method:'GET',headers:{}},res);assert.equal(res.code,200);assert.equal(res.data.user,null);}finally{if(old===undefined)delete process.env.DESCOPE_PROJECT_ID;else process.env.DESCOPE_PROJECT_ID=old;}});
test('invalid recipient input never reaches the invitation provider',async()=>{const old=process.env.DESCOPE_MANAGEMENT_KEY;process.env.DESCOPE_MANAGEMENT_KEY='unit-test-only';try{const service=sdk();service.management.user.invite=()=>assert.fail('must not send');const res=response();await createHandler(()=>service)(request({action:'invite',email:'invalid'}),res);assert.equal(res.code,400);}finally{if(old===undefined)delete process.env.DESCOPE_MANAGEMENT_KEY;else process.env.DESCOPE_MANAGEMENT_KEY=old;}});
