const {test}=require('node:test'),assert=require('node:assert/strict');const {createHandler,currentUser,OWNER_EMAIL}=require('../lib/account.cjs');
process.env.TURNLI_TENANT_ID='test-workspace';process.env.DESCOPE_MANAGEMENT_KEY='unit-test-not-real';
const req=body=>({method:'POST',headers:{origin:'https://turnli.vercel.app','content-type':'application/json',cookie:'__Host-turnly-session=session; __Host-turnly-refresh=refresh'},body});
function res(){return {headers:{},getHeader(k){return this.headers[k]},setHeader(k,v){this.headers[k]=v},status(s){this.code=s;return this},json(data){this.data=data;return this}};}
function sdk(email=OWNER_EMAIL,member=true){return {validateSession:async()=>({token:{}}),me:async token=>{assert.equal(token,'refresh');return {ok:true,data:{userId:email===OWNER_EMAIL?'owner-id':'customer-id',email,verifiedEmail:true,userTenants:member?[{tenantId:'test-workspace'}]:[]}}},management:{user:{invite:async()=>({ok:true})}},logout:async()=>({ok:true})};}
test('anonymous requests cannot send invitations',async()=>{const r=res();await createHandler(()=>sdk())({...req({action:'invite',email:'customer@example.com'}),headers:{origin:'https://turnli.vercel.app','content-type':'application/json'}},r);assert.equal(r.code,401);});
test('verified new account receives only its own workspace',async()=>{const u=await currentUser(req({}),res(),sdk('outside@example.com',false));assert.equal(u.workspaceId,'user:customer-id');assert.equal(u.legacyAccess,false);assert.equal(u.canInvite,false);});
test('customer member cannot invite others',async()=>{const r=res();await createHandler(()=>sdk('customer@example.com'))(req({action:'invite',email:'other@example.com'}),r);assert.equal(r.code,403);});
test('unverified owner cannot access private area',async()=>{const s=sdk();s.me=async()=>({ok:true,data:{email:OWNER_EMAIL,verifiedEmail:false}});assert.equal(await currentUser(req({}),res(),s),null);});
test('cross-origin login is rejected before provider call',async()=>{const q=req({action:'password-login'});q.headers.origin='https://evil.example';const r=res();await createHandler(()=>assert.fail('provider called'))(q,r);assert.equal(r.code,403);});
test('invites grant only this workspace and no admin roles',async()=>{const s=sdk();s.management.user.invite=async(email,options)=>{assert.equal(email,'customer@example.com');assert.deepEqual(options.userTenants,[{tenantId:'test-workspace',roleNames:[]}]);assert.equal(options.roles,undefined);return {ok:true}};const r=res();await createHandler(()=>s)(req({action:'invite',email:'Customer@example.com'}),r);assert.deepEqual(r.data,{sent:true});});
test('failed provider send never claims invitation sent',async()=>{const s=sdk();s.management.user.invite=async()=>({ok:false,code:500});const r=res();await createHandler(()=>s)(req({action:'invite',email:'customer@example.com'}),r);assert(!r.data.sent);});
test('password login uses provider and only returns secure cookies, not tokens',async()=>{const s=sdk();s.password={signIn:async()=>({ok:true,data:{sessionJwt:'session',refreshJwt:'refresh'}})};const r=res();await createHandler(()=>s)(req({action:'password-login',email:OWNER_EMAIL,password:'test-password'}),r);assert.equal(r.code,200);assert(r.headers['Set-Cookie'].every(v=>v.includes('HttpOnly; Secure; SameSite=Lax')));assert(!JSON.stringify(r.data).includes('refresh'));});
test('resend rate limit is exposed with a cooldown',async()=>{const s=sdk();s.otp={signUpOrIn:{email:async()=>({ok:false,code:429})}};const r=res();await createHandler(()=>s)(req({action:'send-code',email:OWNER_EMAIL}),r);assert.equal(r.code,429);assert.equal(r.data.retryAfter,60);});
test('password change requires fresh OTP and provider password policy',async()=>{const s=sdk();let order=[];s.otp={verify:{email:async()=>{order.push('verify');return {ok:true,data:{sessionJwt:'session',refreshJwt:'refresh'}}}}};s.password={update:async(e,p,t)=>{assert.equal(t,'refresh');order.push('update');return {ok:true}}};const r=res();await createHandler(()=>s)(req({action:'set-password',email:OWNER_EMAIL,code:'123456',password:'ValidTest1!'}),r);assert.deepEqual(order,['verify','update']);assert.equal(r.code,200);});
test('expired session refreshes via provider',async()=>{const s=sdk();s.validateSession=async()=>{throw Error('expired')};s.refreshSession=async()=>({jwt:'new-session',refreshJwt:'refresh'});const r=res();assert(await currentUser(req({}),r,s));assert(r.headers['Set-Cookie'][0].includes('new-session'));});
test('signout invalidates provider refresh session and clears cookies',async()=>{const s=sdk();let revoked=false;s.logout=async token=>{assert.equal(token,'refresh');revoked=true;return {ok:true}};const r=res();await createHandler(()=>s)(req({action:'logout'}),r);assert(revoked);assert(r.headers['Set-Cookie'].every(v=>v.includes('Max-Age=0')));});
test('failed revocation is visible and never reports signed out',async()=>{const s=sdk();s.logout=async()=>({ok:false});const r=res();await createHandler(()=>s)(req({action:'logout'}),r);assert.equal(r.code,503);assert(!r.data.ok);});
test('registration uses Descope password signup and requires email verification without cookies',async()=>{const s=sdk();let created=false;s.password={signUp:async(address,password,details)=>{assert.equal(details.email,address);created=true;return {ok:true}}};s.otp={signIn:{email:async()=>({ok:true})}};const r=res();await createHandler(()=>s)(req({action:'register',email:'new@example.com',password:'ValidTest1!'}),r);assert(created);assert.equal(r.data.verificationRequired,true);assert.equal(r.headers['Set-Cookie'],undefined);});
test('successful account creation is independent of unavailable email delivery',async()=>{const s=sdk();s.password={signUp:async()=>({ok:true})};s.otp={signIn:{email:()=>assert.fail('email must be a separate request')}};const r=res();await createHandler(()=>s)(req({action:'register',email:'new@example.com',password:'ValidTest1!'}),r);assert.equal(r.code,201);assert.equal(r.data.accountCreated,true);assert.equal(r.data.verificationRequired,true);assert.equal(r.headers['Set-Cookie'],undefined);});
test('duplicate signup gives a recoverable verification action and never changes password or sends email automatically',async()=>{const s=sdk();s.password={signUp:async()=>({ok:false,code:400,error:{errorCode:'E062107'}}),update:()=>assert.fail('must not overwrite password')};s.otp={signIn:{email:()=>assert.fail('email requires user action')}};const r=res();await createHandler(()=>s)(req({action:'register',email:'new@example.com',password:'ValidTest1!'}),r);assert.equal(r.code,409);assert.equal(r.data.code,'E062107');assert.equal(r.data.nextAction,'verify-existing');assert(r.data.error.includes('has not changed'));assert.equal(r.headers['Set-Cookie'],undefined);});
test('unexpected signup failures include only a safe diagnostic code',async()=>{const s=sdk();s.password={signUp:async()=>({ok:false,code:400,error:{errorCode:'E999999',errorDescription:'sensitive upstream detail'}})};const r=res();await createHandler(()=>s)(req({action:'register',email:'new@example.com',password:'ValidTest1!'}),r);assert(r.data.error.includes('E999999'));assert(!r.data.error.includes('sensitive'));});
test('unverified password login provides verification context without dashboard cookies',async()=>{const s=sdk();s.password={signIn:async()=>({ok:true,data:{sessionJwt:'session',refreshJwt:'refresh'}})};s.me=async()=>({ok:true,data:{userId:'new',email:'new@example.com',verifiedEmail:false}});const r=res();await createHandler(()=>s)(req({action:'password-login',email:'new@example.com',password:'ValidTest1!'}),r);assert.equal(r.code,200);assert.deepEqual(r.data,{verificationRequired:true});assert.equal(r.headers['Set-Cookie'].length,1);assert(r.headers['Set-Cookie'][0].startsWith('__Host-turnli-verification='));assert(r.headers['Set-Cookie'][0].includes('Max-Age=900'));});
test('signup retains provider refresh token only as secure verification context',async()=>{const s=sdk();s.password={signUp:async()=>({ok:true,data:{sessionJwt:'session',refreshJwt:'refresh'}})};const r=res();await createHandler(()=>s)(req({action:'register',email:'new@example.com',password:'ValidTest1!'}),r);assert.equal(r.code,201);assert(r.headers['Set-Cookie'][0].startsWith('__Host-turnli-verification='));assert(!JSON.stringify(r.data).includes('refresh'));});
test('unverified email uses OTP update after authenticating pending context',async()=>{const s=sdk();s.me=async token=>{assert.equal(token,'pending');return {ok:true,data:{userId:'new',email:'new@example.com',verifiedEmail:false}}};s.otp={update:{email:async(...args)=>{assert.deepEqual(args,['new@example.com','new@example.com','pending']);return {ok:true}}},signIn:{email:()=>assert.fail('signin refuses unverified email')}};const q=req({action:'send-code',email:'new@example.com'});q.headers.cookie='__Host-turnli-verification=pending';const r=res();await createHandler(()=>s)(q,r);assert.equal(r.code,200);});
test('pending verification cannot change a different account email',async()=>{const s=sdk();s.me=async()=>({ok:true,data:{userId:'new',email:'first@example.com',verifiedEmail:false}});s.otp={update:{email:()=>assert.fail('must not update other email')},signIn:{email:async()=>({ok:false,code:401,error:{errorCode:'E062115'}})}};const q=req({action:'send-code',email:'other@example.com'});q.headers.cookie='__Host-turnli-verification=pending';const r=res();await createHandler(()=>s)(q,r);assert.equal(r.code,409);assert.equal(r.data.nextAction,'password-verification');});
test('unverified code response never grants dashboard access or reports successful login',async()=>{const s=sdk();s.me=async()=>({ok:true,data:{userId:'new',verifiedEmail:false}});s.otp={verify:{email:async()=>({ok:true,data:{sessionJwt:'session',refreshJwt:'refresh'}})}};const r=res();await createHandler(()=>s)(req({action:'verify-code',email:'new@example.com',code:'123456'}),r);assert.equal(r.code,403);assert.equal(r.headers['Set-Cookie'],undefined);});
