const {test}=require('node:test'),assert=require('node:assert/strict');const {detectSource}=require('../lib/booking-source.cjs'),{segments}=require('../src/features/calendar/layout.ts');
for(const [source,url] of [['Airbnb','https://www.airbnb.com/calendar/ical/abc'],['Booking.com','https://admin.booking.com/calendar'],['Vrbo','https://www.vrbo.com/ical'],['Houfy','https://www.houfy.com/calendar']])test(source+' detection requires first-party metadata',()=>{assert.equal(detectSource({feedURL:url}).source,source);assert.equal(detectSource({description:'Channel: '+source}).source,source);assert.equal(detectSource({description:'A guest mentioned '+source}).source,null);});
test('unknown/conflicting metadata and lookalike domains stay neutral',()=>{assert.equal(detectSource({feedURL:'https://airbnb.com.evil.example/feed',description:'Airbnb host John'}).sourceKey,'unknown');assert.equal(detectSource({fields:['Airbnb','Vrbo']}).source,null);assert.equal(detectSource({eventURL:'https://booking.com/r',feedURL:'https://aggregator.example/feed'}).source,'Booking.com');});
const booking=(id,start,end)=>({id,arrival:{date:start},checkout:{date:end},sourceKey:'airbnb'});
test('multi-week segments retain one ID with accurate continuation endpoints',()=>{const b=booking('same','2026-09-13','2026-09-30');const first=segments([b],'2026-09-07')[0],middle=segments([b],'2026-09-14')[0],last=segments([b],'2026-09-28')[0];assert.equal(first.booking.id,last.booking.id);assert.equal(first.continuesBefore,false);assert.equal(first.continuesAfter,true);assert.equal(middle.continuesBefore,true);assert.equal(middle.continuesAfter,true);assert.equal(last.continuesBefore,true);assert.equal(last.continuesAfter,false);assert.equal(last.booking.sourceKey,'airbnb');});
test('adjacent checkout/check-in stays share a lane without merging reservations',()=>{const result=segments([booking('a','2026-09-14','2026-09-16'),booking('b','2026-09-16','2026-09-18')],'2026-09-14');assert.equal(result.length,2);assert.equal(result[0].lane,result[1].lane);assert(result[0].last<=result[1].first);});
test('overlapping reservations occupy separate compact lanes',()=>{const result=segments([booking('a','2026-09-14','2026-09-18'),booking('b','2026-09-16','2026-09-19')],'2026-09-14');assert.notEqual(result[0].lane,result[1].lane);assert(result.every(b=>b.first>=0&&b.last<=14));});
const {createHandler:calendarHandler}=require('../src/server/handlers/calendar.js');
function response(){return {setHeader(){},status(code){this.code=code;return this},json(data){this.data=data;return this}};}
test('seen acknowledgement uses authenticated user/workspace and only owned booking IDs',async()=>{const calls=[],r=response();await calendarHandler(async()=>({role:'host',id:'cleaner',workspaceId:'workspace'}),()=>({list:async()=>[{id:'calendar',bookings:[{id:'real'}]}]}),undefined,()=>({acknowledge:async(...args)=>calls.push(args)}))({method:'POST',headers:{origin:'https://turnli.vercel.app','content-type':'application/json'},body:{action:'seen',ids:['foreign:booking','calendar:real'],owner:'foreign'}},r);assert.equal(r.code,200);assert.deepEqual(calls,[['workspace','cleaner','calendar',['real']]]);});
test('sidebar preference is scoped to the authenticated account, not caller IDs',async()=>{const {createHandler}=require('../src/server/handlers/dashboard.js'),r=response();await createHandler(async()=>({role:'cleaner',id:'cleaner',workspaceId:'workspace'}),()=>assert.fail('workspace document not needed'),()=>({savePreferences:async(...args)=>{assert.deepEqual(args,['workspace','cleaner',true]);return {sidebarCollapsed:true}}}))({method:'POST',headers:{origin:'https://turnli.vercel.app','content-type':'application/json'},body:{action:'preferences',sidebarCollapsed:true,user:'another'}},r);assert.deepEqual(r.data,{sidebarCollapsed:true});});
test('same event UID in different calendars remains two distinct reservations',async()=>{const rows=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222'].map((id,i)=>({id,display_name:'Property '+i,enabled:true,feed_host:'unknown.example',check_in:'15:00',check_out:'10:00',bookings:[{id:'shared-uid',guests:null,arrival:{date:'2026-09-15',time:'15:00'},checkout:{date:'2026-09-18',time:'10:00'}}]}));const r=response();await calendarHandler(async()=>({role:'host',id:'test',workspaceId:'workspace'}),()=>({list:async()=>rows}),undefined,()=>({seen:async()=>new Set()}))({method:'GET',query:{month:'2026-09'}},r);assert.equal(r.data.calendars.length,2);assert.equal(r.data.bookings.length,2);assert.notEqual(r.data.bookings[0].id,r.data.bookings[1].id);assert(r.data.bookings.every(b=>b.source===null&&b.guests===null));});
const {timezoneLabel}=require('../src/features/calendar/layout.ts');
test('London timezone follows displayed dates including DST transition months',()=>{
 assert.equal(timezoneLabel('2026-01-01','2026-01-31'),'GMT');
 assert.equal(timezoneLabel('2026-07-01','2026-07-31'),'BST');
 assert.equal(timezoneLabel('2026-03-01','2026-03-31'),'GMT / BST');
 assert.equal(timezoneLabel('2026-10-01','2026-10-31'),'BST / GMT');
});
