const {test}=require('node:test'),assert=require('node:assert/strict'),{parseCalendar}=require('../lib/calendar.cjs');const {createHandler}=require('../src/server/handlers/calendar.js');
const feed=(dates,extra='')=>`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:test-reservation\r\nSUMMARY:Reserved: Test Guest 4 guests\r\n${dates}\r\n${extra}END:VEVENT\r\nEND:VCALENDAR`;
const dates='DTSTART;TZID=Europe/London:20260915T150000\r\nDTEND;TZID=Europe/London:20260918T100000';
test('parses actual stay span, summary, UID, guests and checkout',()=>{const b=parseCalendar(feed(dates)).bookings[0];assert.equal(b.id,require('node:crypto').createHash('sha256').update('test-reservation').digest('hex'));assert.equal(b.title,undefined);assert.equal(b.summary,undefined);assert(!JSON.stringify(b).includes('Test Guest'));assert.equal(b.guests,4);assert.equal(b.arrival.date,'2026-09-15');assert.equal(b.checkout.date,'2026-09-18');assert.equal(b.checkout.time,'10:00');});
test('all-day DTEND remains exclusive checkout date and times come from explicit rules',()=>{const raw=feed('DTSTART;VALUE=DATE:20260915\r\nDTEND;VALUE=DATE:20260918');const b=parseCalendar(raw,{checkIn:'15:00',checkOut:'10:00'}).bookings[0];assert.equal(b.checkout.date,'2026-09-18');assert.equal(b.checkout.timeSource,'property-rule');assert.equal(parseCalendar(raw).bookings[0].checkout.time,null);});
test('UTC converts with UK DST',()=>{const b=parseCalendar(feed('DTSTART:20260915T140000Z\r\nDTEND:20260918T090000Z')).bookings[0];assert.equal(b.arrival.time,'15:00');assert.equal(b.checkout.time,'10:00');});
test('cancelled events excluded; malformed and unsupported events fail rather than empty calendar',()=>{assert.equal(parseCalendar(feed(dates,'STATUS:CANCELLED\r\n')).bookings.length,0);assert.throws(()=>parseCalendar('invalid'));assert.throws(()=>parseCalendar(feed(dates,'RRULE:FREQ=WEEKLY\r\n')));assert.throws(()=>parseCalendar(feed('DTSTART:20260915T150000Z')));});
function res(){return {headers:{},setHeader(k,v){this.headers[k]=v},status(s){this.code=s;return this},json(data){this.data=data;return this}};}
test('calendar and subscription require authentication before fetch',async()=>{for(const query of [{},{action:'subscription'}]){const r=res();await createHandler(async()=>null,()=>assert.fail('must not fetch'))({method:'GET',query},r);assert.equal(r.code,401);assert(!r.data.url);}});
test('no subscriptions and database outage are distinct states',async()=>{const r=res();await createHandler(async()=>({role:'cleaner',id:'a',workspaceId:'user:a'}),()=>({list:async()=>[]}))({method:'GET'},r);assert.equal(r.data.state,'not-connected');const bad=res();await createHandler(async()=>({role:'cleaner',id:'a',workspaceId:'user:a'}),()=>({list:async()=>{throw Error('offline')}}))({method:'GET'},bad);assert.equal(bad.code,503);assert(!bad.data.bookings);});
