const {test}=require('node:test'),assert=require('node:assert/strict');
const {createHandler,change}=require('../src/server/handlers/dashboard.js');
const empty={properties:[]};
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v},status(c){this.code=c;return this},json(v){this.data=v;return this}};}
const request=(body,method='POST')=>({method,body,headers:{origin:'https://turnli.vercel.app','content-type':'application/json'}});
test('dashboard requires authentication before any database access',async()=>{const r=response();await createHandler(async()=>null,()=>assert.fail('must not access store'))(request(null,'GET'),r);assert.equal(r.code,401);});
test('dashboard uses authenticated workspace only, ignoring caller owner',async()=>{const r=response();await createHandler(async()=>({role:'host',id:'test',workspaceId:'user:actual'}),()=>({load:async owner=>{assert.equal(owner,'user:actual');return {revision:0,data:empty}},save:async(owner,revision,data)=>{assert.equal(owner,'user:actual');return {revision:1,data}}}))(request({owner:'user:other',revision:0,action:'property',name:'My property',phone:'',notes:''}),r);assert.equal(r.code,200);assert.equal(r.data.data.properties[0].name,'My property');});
test('cross-origin dashboard mutation is rejected',async()=>{const r=response(),q=request({});q.headers.origin='https://other.example';await createHandler(()=>assert.fail('auth not needed'))(q,r);assert.equal(r.code,403);});
test('property content and completion persist in document independently',()=>{let d=change(empty,{action:'property',name:'One',phone:'+447773333455',notes:'Instructions'}),id=d.properties[0].id;d=change(d,{action:'content',id,kind:'regular',items:['Kitchen','Bedroom']});d=change(d,{action:'content',id,kind:'deep',items:['Oven']});d=change(d,{action:'content',id,kind:'faqs',items:[{question:'When?',answer:'Check the calendar.'}]});d=change(d,{action:'check',id,kind:'regular',index:0,checked:true});assert.deepEqual(d.properties[0].checked,{regular:[0],deep:[]});assert.equal(d.properties[0].faqs[0].answer,'Check the calendar.');d=change(d,{action:'reset',id,kind:'regular'});assert.deepEqual(d.properties[0].checked.regular,[]);assert.equal(d.properties[0].regular.length,2);assert.deepEqual(empty,{properties:[]});});
test('foreign property IDs and invalid content are rejected',()=>{const d=change(empty,{action:'property',name:'One',phone:'',notes:''});assert.throws(()=>change(d,{action:'content',id:'foreign',kind:'regular',items:['Task']}));assert.throws(()=>change(d,{action:'content',id:d.properties[0].id,kind:'faqs',items:[{question:'Q',answer:''}]}));});
test('stale revisions cannot overwrite another save',async()=>{const r=response();await createHandler(async()=>({role:'host',id:'test',workspaceId:'user:one'}),()=>({load:async()=>({revision:2,data:empty}),save:()=>assert.fail('stale save')}))(request({revision:1}),r);assert.equal(r.code,409);});
test('concurrent database compare-and-swap failure returns conflict',async()=>{const r=response();await createHandler(async()=>({role:'host',id:'test',workspaceId:'user:one'}),()=>({load:async()=>({revision:0,data:empty}),save:async()=>undefined}))(request({revision:0,action:'property',name:'One',phone:'',notes:''}),r);assert.equal(r.code,409);});
test('legacy checklist progress remains restricted to the original workspace',async()=>{const r=response();await createHandler(async()=>({role:'host',id:'test',workspaceId:'user:new',legacyAccess:false}),()=>({load:async()=>({revision:0,data:empty}),save:()=>assert.fail('must not save legacy progress')}))(request({revision:0,action:'legacy-progress',kind:'regular',state:{checked:[true]}}),r);assert.equal(r.code,403);});
test('legacy regular and deep progress persist separately',()=>{let d=change(empty,{action:'legacy-progress',kind:'regular',state:{checked:[true,false],cleaner:'Cleaner'}});d=change(d,{action:'legacy-progress',kind:'deep',state:{checked:[false,true]}});assert.deepEqual(d.legacyProgress.regular.checked,[true,false]);assert.deepEqual(d.legacyProgress.deep.checked,[false,true]);});
test('template adoption rejects unmatched exclusions without persisting a replacement',async()=>{
 const r=response(),data={properties:[{id:'p',regular:['Property-specific task'],deep:[],notApplicable:{regular:[0],deep:[]},checked:{regular:[],deep:[]}}]};
 await createHandler(async()=>({role:'host',id:'host',workspaceId:'owner'}),()=>({load:async()=>({revision:0,data}),save:()=>assert.fail('must preserve unresolved applicability')}))(request({revision:0,action:'template',id:'p',kind:'regular'}),r);
 assert.equal(r.code,409);assert.match(r.data.error,/no settings were changed/);assert.deepEqual(data.properties[0].notApplicable.regular,[0]);
});
