import AcquisitionPage from '../../../features/marketing/AcquisitionPage';
import { publicMetadata, publicPages } from '../../../features/marketing/metadata';
import './glasgow.css';

export const metadata = publicMetadata(publicPages[4]);
export default function Page() {
  return <AcquisitionPage page={publicPages[4]} parent={publicPages[1]}>
    <section className="public-container acquisition-hero" aria-labelledby="glasgow-title">
      <div className="hero-copy"><p className="eyebrow">For Glasgow Airbnb & holiday let Hosts</p><h1 id="glasgow-title">Airbnb cleaning in Glasgow, <em>managed from booking to guest-ready.</em></h1>
        <p className="public-lead">From flats and apartments to houses, cottages and serviced accommodation, a good changeover starts with the details. Bring your calendar, cleaning brief and Cleaner together in Turnli.</p>
        <div className="public-actions"><a className="public-button" href="/register" aria-describedby="price-next-step">Get your cleaning price <span aria-hidden="true">↗</span></a><a className="public-text-link" href="#your-cleaner">Already have a Cleaner?</a></div>
        <p id="price-next-step" className="local-conversion-note">Property-specific fixed pricing is being developed, with your price shown before an account is needed. For now, this button opens registration; it does not calculate a quote or book a Cleaner.</p>
      </div>
      <aside className="acquisition-note local-intro" aria-labelledby="glasgow-start"><p className="eyebrow">Two ways to get organised</p><h2 id="glasgow-start">Need a Cleaner?<br />Or bringing your own?</h2><p>We’re developing Cleaner availability in Glasgow. The reference prices below help you plan, but there is no guarantee of a match or immediate availability.</p><p>Already have someone you trust? With a Host workspace, invite them to the property and manage upcoming cleans, instructions and completed work together.</p><a className="public-text-link" href="#reference-prices">See reference prices <span aria-hidden="true">↓</span></a></aside>
    </section>

    <section id="reference-prices" className="public-container public-section acquisition-section" aria-labelledby="prices-title" data-reveal>
      <p className="eyebrow">A clear starting point</p><h2 id="prices-title">Regular or Deep.<br />A price for the work involved.</h2><p className="section-lead">These starting prices use the reference property below. They are not a fixed quote for every Glasgow property, or a confirmed offer of Cleaner availability.</p>
      <div className="acquisition-grid local-prices">
        <article><h3>Regular Airbnb cleaning</h3><p className="local-price">From <strong>£60</strong></p><p>For routine turnovers using the standard <strong>38-task Regular Clean</strong>.</p><p>Reference duration: approximately <strong>2–2.25 hours</strong>.</p></article>
        <article><h3>Deep cleaning</h3><p className="local-price">From <strong>£130</strong></p><p>For more detailed work using the standard <strong>109-task Deep Clean</strong>.</p><p>Reference duration: approximately <strong>4–4.5 hours</strong>.</p></article>
      </div>
      <div className="local-reference"><h3>The reference setup</h3><dl><div><dt>Property size</dt><dd>Approximately 52 m²</dd></div><div><dt>Bedrooms / bathrooms</dt><dd>2 bedrooms · 1 bathroom</dd></div><div><dt>Cleaning brief</dt><dd>Standard Turnli checklist</dd></div><div><dt>Included in these reference prices</dt><dd>Cleaner supplies and linen/towel wash and dry</dd></div></dl><p>Different layouts, beds, laundry loads, access arrangements and cleaning requirements can change the work and time needed. The durations are estimates for this reference setup.</p></div>
      <div className="local-brief"><h3>A fixed price starts with your property details</h3><p>The planned quote flow will use the property address, bedrooms, beds, bathrooms, size in m² or ft² where known, cleaning frequency, Regular/Deep/both, supplies, linen/towel wash and dry, and any other relevant requirements. You’ll see your fixed Turnli cleaning price based on that brief before creating an account or logging in. An account will only be needed to save, post or proceed with your requirement.</p><p>For now, Get your cleaning price takes you to account registration. It does not collect those details or calculate a quote yet.</p></div>
    </section>

    <section className="product-band"><div className="public-container acquisition-split" data-reveal><div><p className="eyebrow">The Glasgow handover</p><h2>Plan for the building,<br />not just the booking.</h2><p className="section-lead">For a Glasgow changeover, access arrangements and the layout of the property can matter as much as the floor area.</p></div><div className="local-context">
      <h3>Tenements and shared closes</h3><p>Where a property has a shared close—the communal entrance and stair—record the correct flat position, floor, entry procedure and where equipment is kept in the secure Start Guide. Keep access codes out of public listings and cleaning task lists. Shared-space cleaning should be agreed separately from the flat’s own tasks.</p>
      <h3>City-centre and serviced accommodation</h3><p>Clarify any reception handover, lift access, loading restrictions or parking arrangements before the clean. Record building-specific refuse and recycling instructions so the Cleaner has a usable brief on arrival.</p>
      <h3>Laundry within the changeover window</h3><p>Count the beds and linen sets, not just bedrooms. Agree where washing and drying happen, allow for machine cycles and identify spare linen if the next arrival leaves a short window. Included laundry in the reference price does not make every load fit the same timetable.</p>
      <p>These are property-planning examples, not a claim of service coverage or building approval. Scottish short-term lets operate within a licensing system; <a className="public-text-link" href="https://www.mygov.scot/short-term-let-licences">check the official short-term-let guidance</a> for your property. Turnli’s cleaning workflow does not establish licensing or planning compliance.</p>
    </div></div></section>

    <section className="public-container public-section acquisition-section" aria-labelledby="standard-title" data-reveal>
      <p className="eyebrow">A standard that stays with the job</p><h2 id="standard-title">From the reservation<br />to a reviewed clean.</h2><p className="section-lead">Turnli supports the operational handover. When you bring an existing Cleaner, this workflow is available in your Host workspace today.</p><p className="section-lead">The standards cover arrival checks, kitchens, bathrooms, bedrooms, living areas and final checks. The Deep Clean includes more detailed work such as cleaning inside kitchen cupboards; property applicability keeps irrelevant tasks out of the brief.</p>
      <ol className="acquisition-grid acquisition-workflow">
        <li><span className="step-number">01</span><h3>Plan and assign</h3><p>Link the property’s reservation calendar and assign its Cleaner. Eligible reservations create planned turnover jobs after scheduled checkout. A calendar date does not confirm that the guest has physically left.</p></li>
        <li><span className="step-number">02</span><h3>Give the right brief</h3><p>Use the Regular or Deep standard and mark irrelevant tasks not applicable. Each job keeps its own checklist. The assigned Cleaner can open the secure Property Start Guide for operational instructions.</p></li>
        <li><span className="step-number">03</span><h3>Record and review</h3><p>The Cleaner can report an issue during the clean, complete the checklist and submit 3–6 completion photos. The Host reviews the evidence and approves the clean or reports an issue.</p></li>
      </ol><a className="public-text-link" href="/#operations">See Turnli’s standard checklist approach <span aria-hidden="true">↗</span></a>
    </section>

    <section id="your-cleaner" className="product-band"><div className="public-container acquisition-split" data-reveal><div><p className="eyebrow">Keep the relationship you trust</p><h2>Already have<br />a Cleaner?</h2></div><div><p>You don’t need to find someone new. Invite your existing Cleaner to the property so they can see its operational calendar, upcoming jobs, applicable checklist and authorised Start Guide without copying your private iCal feed.</p><p>They establish their own login. Cleaning issues and submitted evidence stay with the job, without unnecessary sharing of personal contact information.</p><div className="public-actions"><a className="public-button" href="/register">Invite them to Turnli free <span aria-hidden="true">↗</span></a></div><p className="local-conversion-note">Create an account to start. Host workspace access is required to invite a Cleaner.</p><a className="public-text-link" href="/software/airbnb-cleaning">Explore the cleaning software <span aria-hidden="true">↗</span></a></div></div></section>

    <section className="public-container public-section acquisition-section" aria-labelledby="local-cleaners-title" data-reveal><p className="eyebrow">For independent Cleaners & cleaning businesses</p><h2 id="local-cleaners-title">Clean Airbnbs<br />in Glasgow.</h2><p className="section-lead">Join Turnli free to manage your existing Airbnb and holiday-let customers, calendars and cleaning schedules. Work assigned by Turnli Hosts can sit alongside your own customer properties.</p><p className="section-lead">As Turnli grows in Glasgow, we’re developing new cleaning opportunities. Availability depends on real Host demand; joining does not guarantee work or income.</p><a className="public-text-link" href="/cleaners/airbnb-cleaning-jobs/">Explore Turnli for Cleaners <span aria-hidden="true">↗</span></a></section>

    <section className="public-container public-section acquisition-section" aria-labelledby="glasgow-questions"><h2 id="glasgow-questions">Before the next changeover.</h2><div className="local-questions">
      <details><summary>Is £60 the price for my property?</summary><p>No. It is the Regular Clean starting price for the approximately 52 m², two-bedroom, one-bathroom reference setup above. A property-specific fixed quote needs the full cleaning brief. Online quoting is still being developed.</p></details>
      <details><summary>Are supplies and laundry included?</summary><p>Cleaner supplies and linen/towel wash and dry are included in the reference prices. Your brief should still specify the beds, linen quantities, washing and drying arrangements, and any particular supply requirements.</p></details>
      <details><summary>Does a planned turnover mean the property is empty?</summary><p>No. Turnli plans from scheduled reservation dates. Confirm access and any change to departure arrangements separately; a scheduled checkout is not proof of physical checkout.</p></details>
    </div></section>
    <section className="final-cta" aria-labelledby="glasgow-final"><div className="public-container"><p className="eyebrow">Your Glasgow property. A clearer plan.</p><h2 id="glasgow-final">Give the next clean<br />a proper handover.</h2><p>Explore your starting price or bring the Cleaner you already know.</p><div className="public-actions"><a className="public-button" href="/register" aria-describedby="final-price-note">Get your cleaning price <span aria-hidden="true">↗</span></a></div><p id="final-price-note">Online quotes and Cleaner matching are still being developed. For now, this button opens registration; it does not calculate a quote.</p><a className="local-national-link" href="/airbnb-cleaning">Explore Airbnb cleaning with Turnli</a></div></section>
  </AcquisitionPage>;
}
