import AcquisitionPage from '../../../features/marketing/AcquisitionPage';
import { publicMetadata, publicPages } from '../../../features/marketing/metadata';
import '../../../features/marketing/local.css';

export const metadata = publicMetadata(publicPages[5]);
export default function Page() {
  return <AcquisitionPage page={publicPages[5]} parent={publicPages[1]}>
    <section className="public-container acquisition-hero" aria-labelledby="edinburgh-title">
      <div className="hero-copy"><p className="eyebrow">For Edinburgh Airbnb & holiday let Hosts</p><h1 id="edinburgh-title">Airbnb cleaning in Edinburgh, <em>ready for the next handover.</em></h1>
        <p className="public-lead">A festival-week changeover or a longer holiday stay needs a clear cleaning brief. Organise your flat, house, cottage or serviced accommodation around the actual work, linen and time available.</p>
        <div className="public-actions"><a className="public-button" href="/quote" aria-describedby="price-next-step">Get your cleaning price <span aria-hidden="true">↗</span></a><a className="public-text-link" href="#your-cleaner">Already have a Cleaner?</a></div>
        <p id="price-next-step" className="local-conversion-note">See your fixed property-specific price without an account. Create an account or log in only when you choose to save and continue.</p>
      </div>
      <aside className="acquisition-note local-intro" aria-labelledby="edinburgh-start"><p className="eyebrow">Before the busy dates</p><h2 id="edinburgh-start">The next arrival starts<br />with this clean.</h2><p>Check the gap between planned departure and arrival, the beds to turn over and the linen ready to use. A calendar slot alone does not tell you whether the work will fit.</p><p>Need a Cleaner? Turnli’s marketplace availability in Edinburgh is developing. A quote is not a booking or a guarantee of a match.</p></aside>
    </section>

    <section className="product-band"><div className="public-container acquisition-split" data-reveal><div><p className="eyebrow">An Edinburgh changeover brief</p><h2>Plan the busy period.<br />Keep each stay individual.</h2><p className="section-lead">Edinburgh’s August festivals are a useful point to review your handovers. Use the <a className="public-text-link" href="https://www.edinburghfestivalcity.com/plan-your-trip/faqs">official Edinburgh Festivals planning information</a> alongside your own bookings; event dates are not reservation data.</p></div><div className="local-context">
      <h3>Check each departure-to-arrival window</h3><p>If your holiday let has back-to-back stays, agree the cleaning window with your Cleaner before the busy dates. A later departure, extra bed or longer laundry cycle can change the plan. Turnli schedules eligible turnover jobs from reservation checkout dates; it does not confirm that a guest has physically left.</p>
      <h3>Make linen turnover practical</h3><p>Record the bed sizes and sets needed for the next stay, where clean spares are kept and whether washing and drying can finish in the available window. If there is little time between stays, agree a spare-linen plan rather than assuming every load will be ready.</p>
      <h3>Give the right entrance and floor</h3><p>For a traditional tenement, identify the shared entrance, stair and exact flat position. For a house or cottage, note separate entrances and where equipment is stored. Keep entry details in the secure Property Start Guide, separate from the cleaning task list.</p>
      <h3>Keep property permissions separate</h3><p>Check Edinburgh’s <a className="public-text-link" href="https://www.edinburgh.gov.uk/licences-permits/licences-permits-applications/10">official short-term-let licensing and planning guidance</a> for your circumstances. Organising a clean through Turnli does not establish permission to let the property.</p>
    </div></div></section>

    <section id="reference-prices" className="public-container public-section acquisition-section" aria-labelledby="prices-title" data-reveal>
      <p className="eyebrow">Know the price before you sign up</p><h2 id="prices-title">Price the property,<br />not the season.</h2><p className="section-lead">Regular Airbnb cleaning starts from £60; Deep cleaning starts from £130. Your fixed price comes from the shared Turnli quote flow using your property details, not an Edinburgh event surcharge.</p>
      <div className="acquisition-grid local-prices"><article><h3>Regular Airbnb cleaning</h3><p className="local-price">From <strong>£60</strong></p><p>The 38-task Regular Clean standard for routine changeovers.</p></article><article><h3>Deep cleaning</h3><p className="local-price">From <strong>£130</strong></p><p>The 109-task Deep Clean standard for more detailed work.</p></article></div>
      <div className="local-brief"><h3>Tell us what needs cleaning</h3><p>Enter the location, bedrooms, beds, bathrooms and floor area if known. You can still get a price without knowing the size. Cleaning supplies and normal linen/towel wash and dry are included. The starting prices are not the price of every property; inaccurate or materially incomplete details may require recalculation.</p><p>Cleaning frequency does not change the current price. <a className="public-text-link" href="/quote">Calculate your Regular or Deep cleaning price</a> before deciding whether to save the requirement.</p></div>
    </section>

    <section className="public-container public-section acquisition-section" aria-labelledby="handover-title" data-reveal><p className="eyebrow">A brief that stays with the work</p><h2 id="handover-title">From the linen cupboard<br />to the final check.</h2><div className="acquisition-grid">
      <article><h3>Prepare the property</h3><p>Assign your Cleaner, link the reservation calendar and mark irrelevant standard tasks not applicable. The job receives its own checklist; access and appliance instructions belong in the secure Start Guide.</p></article>
      <article><h3>Record problems during the clean</h3><p>Your assigned Cleaner can report an issue against the job so the problem has context. Agree any change to the next guest’s arrival separately; reporting an issue does not resolve the timing for you.</p></article>
      <article><h3>Review before the handover</h3><p>The Cleaner completes the checklist and submits 3–6 completion photos. You review the submitted evidence and approve the clean or report an issue.</p></article>
    </div><a className="public-text-link" href="/#operations">See Turnli’s standard checklist approach <span aria-hidden="true">↗</span></a></section>

    <section id="your-cleaner" className="product-band"><div className="public-container acquisition-split" data-reveal><div><p className="eyebrow">Keep local knowledge</p><h2>Already have<br />a Cleaner?</h2></div><div><p>If your Cleaner already knows the property, keep that relationship. With a Host workspace, invite them to Turnli and give them the authorised calendar, upcoming jobs, applicable checklist and read-only Start Guide.</p><p>They use their own login. You do not need to share your private iCal feed or put access instructions in a public listing.</p><a className="public-text-link" href="/register">Invite your existing Cleaner to Turnli <span aria-hidden="true">↗</span></a><p className="local-conversion-note">Create an account to start. Host workspace access is required to send property invitations.</p><a className="public-text-link" href="/software/airbnb-cleaning">See how to manage work with your Cleaner</a></div></div></section>

    <section className="public-container public-section acquisition-section" aria-labelledby="cleaners-title" data-reveal><p className="eyebrow">For independent Cleaners & cleaning businesses</p><h2 id="cleaners-title">Clean Airbnbs in Edinburgh.</h2><p className="section-lead">Join Turnli free to manage your existing holiday-let customers, calendars and cleaning schedules. Keep each property’s work clear when several customers have changeovers on the same day.</p><p className="section-lead">New Turnli cleaning opportunities depend on local Host demand and developing marketplace availability. Joining does not guarantee jobs or income.</p><a className="public-text-link" href="/cleaners/airbnb-cleaning-jobs/">Explore Turnli for Cleaners <span aria-hidden="true">↗</span></a></section>

    <section className="public-container public-section acquisition-section" aria-labelledby="questions-title"><h2 id="questions-title">Planning an Edinburgh turnover?</h2><div className="local-questions">
      <details><summary>Does a festival stay change my cleaning price?</summary><p>The current quote model uses property details, with no seasonal or frequency surcharge. The time available for a changeover still needs to be agreed with your Cleaner; a fixed quote does not guarantee availability for a festival date.</p></details>
      <details><summary>What if laundry cannot finish before the next arrival?</summary><p>Plan spare clean sets and agree the washing and drying arrangements in advance. Normal linen/towel wash and dry are included in the quote, but machine cycles and the number of sets still matter. Keep the linen locations and appliance instructions in the Start Guide.</p></details>
      <details><summary>Can Turnli confirm that my holiday let is licensed?</summary><p>No. Use the council guidance linked above to check the property’s requirements. A quote, calendar connection or completed checklist is not a licensing or planning check.</p></details>
    </div></section>
    <section className="final-cta" aria-labelledby="final-title"><div className="public-container"><p className="eyebrow">A clearer Edinburgh changeover</p><h2 id="final-title">Start with the property.<br />See the price.</h2><p>No account needed to calculate your cleaning price. Save and continue when you’re ready.</p><div className="public-actions"><a className="public-button" href="/quote">Get your cleaning price <span aria-hidden="true">↗</span></a></div><a className="local-national-link" href="/airbnb-cleaning">Explore Airbnb cleaning with Turnli</a></div></section>
  </AcquisitionPage>;
}
