import AcquisitionPage from '../../../features/marketing/AcquisitionPage';
import { publicMetadata, publicPages } from '../../../features/marketing/metadata';

export const metadata = publicMetadata(publicPages[2]);
const workflow = [
  ['Reservation calendar', 'Connect a property’s iCal feed to keep reservation dates visible. Your Cleaner sees operational dates, without receiving your private feed URL.'],
  ['Planned turnover', 'Eligible reservations create planned cleaning jobs after scheduled checkout. Changes update planned work safely; completed cleaning history is preserved.'],
  ['Cleaner assignment', 'Invite your existing Cleaner by email and assign them to the property. Future routine turnover jobs use that relationship, without repeated manual assignment.'],
  ['The right checklist', 'Each job keeps its own persisted checklist. Start with 38 Regular or 109 Deep Clean tasks and mark standard tasks not applicable for the property.'],
  ['Issues in context', 'An assigned Cleaner can report an issue during the clean. The report stays with the job and property for the authorised Host to view.'],
  ['Photos and Host review', 'The Cleaner completes the checklist, uploads 3–6 photos and submits. Review the saved evidence, then approve the clean or report an issue.'],
];
export default function Page() {
  return <AcquisitionPage page={publicPages[2]}>
    <section className="public-container acquisition-hero" aria-labelledby="software-title"><div className="hero-copy"><p className="eyebrow">Airbnb cleaning management software</p><h1 id="software-title">Already have a Cleaner? <em>Put it all in one place.</em></h1><p className="public-lead">Keep your Airbnb cleaning operations together, from the reservation calendar to Host review. Built for Hosts, property managers and cleaning businesses with existing Cleaner relationships.</p><div className="public-actions"><a className="public-button" href="/register">Get started <span aria-hidden="true">↗</span></a><a className="public-text-link" href="#workflow">See the workflow <span aria-hidden="true">↓</span></a></div></div>
      <aside className="acquisition-note" aria-labelledby="one-workflow"><p className="eyebrow">From reservation to review</p><h2 id="one-workflow">One property.<br />One clear handover.</h2><p>The calendar shows the stay. The cleaning job records the work. Your checklist, Start Guide, reported issues and completion evidence stay connected to the right property.</p><p>Turnli focuses on cleaning operations. It is not a full property-management system.</p></aside></section>
    <section id="workflow" className="public-container public-section acquisition-section" aria-labelledby="workflow-title" data-reveal><p className="eyebrow">A practical workflow</p><h2 id="workflow-title">From the next stay<br />to a reviewed clean.</h2><ol className="acquisition-grid acquisition-workflow">{workflow.map(([title, copy], index) => <li key={title}><span className="step-number">0{index + 1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol><p className="workflow-note">Scheduled checkout is a planning date, not confirmation that the guest has physically checked out.</p></section>
    <section className="product-band"><div className="public-container acquisition-split" data-reveal><div><p className="eyebrow">Shared work. Appropriate access.</p><h2>The details,<br />with the right people.</h2></div><div><p>Hosts manage their properties, calendars and assignments. Cleaners receive a read-only operational calendar and secure property guidance only while authorised. Access instructions stay separate from cleaning task lists.</p><p>Cleaners can also manage their own customer properties and feeds alongside Host-assigned work. Each workspace keeps its own administration and private information.</p><a className="public-text-link" href="/cleaners/airbnb-cleaning-jobs/">See the Cleaner workspace <span aria-hidden="true">↗</span></a><p className="related-link">Preparing a property brief? Our guides cover building handovers in <a href="/airbnb-cleaning/glasgow">Glasgow</a>, festival-period planning in <a href="/airbnb-cleaning/edinburgh">Edinburgh</a> and travel between properties in <a href="/airbnb-cleaning/london">London</a>.</p><p className="related-link">Still looking for someone? <a href="/airbnb-cleaning">Explore Airbnb cleaning with Turnli.</a></p></div></div></section>
    <section className="final-cta" aria-labelledby="software-start"><div className="public-container"><p className="eyebrow">Keep the relationship. Simplify the work.</p><h2 id="software-start">Your next turnover,<br />a little more organised.</h2><p>Create an account to get started with Turnli.</p><div className="public-actions"><a className="public-button" href="/register">Get started <span aria-hidden="true">↗</span></a></div></div></section>
  </AcquisitionPage>;
}
