import AcquisitionPage from '../../../features/marketing/AcquisitionPage';
import { publicMetadata, publicPages } from '../../../features/marketing/metadata';

export const metadata = publicMetadata(publicPages[3]);
export default function Page() {
  return <AcquisitionPage page={publicPages[3]}>
    <section className="public-container acquisition-hero" aria-labelledby="jobs-title"><div className="hero-copy"><p className="eyebrow">For independent Cleaners & cleaning businesses</p><h1 id="jobs-title">Find Airbnb cleaning jobs <em>near you.</em></h1><p className="public-lead">Join Turnli free to manage your existing Airbnb customers, calendars and cleans. As Turnli grows in your area, we’re building opportunities for you to work with more Hosts.</p><div className="public-actions"><a className="public-button" href="/register">Join Turnli free <span aria-hidden="true">↗</span></a><a className="public-text-link" href="/login">Already a member? Log in</a></div></div>
      <aside className="acquisition-note" aria-labelledby="today-title"><p className="eyebrow">Useful today. Growing with you.</p><h2 id="today-title">Bring the customers<br />you already have.</h2><p>You can organise your own customer properties and iCal feeds now. If a Turnli Host invites you, sign in with the invited email and accept the property assignment to see the work.</p><p>New holiday let cleaning work depends on local Host demand and availability. Joining does not guarantee jobs or income.</p></aside></section>
    <section className="public-container public-section acquisition-section" aria-labelledby="day-title" data-reveal><p className="eyebrow">A workspace for the working day</p><h2 id="day-title">Know what’s next.<br />Keep the details close.</h2><div className="acquisition-grid">
      <article><h3>Your customers and calendars</h3><p>Add properties for your existing customers and manage their iCal feeds in your own workspace. Keep this separate from read-only calendars shared by Turnli Hosts.</p></article>
      <article><h3>Assigned work, ready to open</h3><p>See upcoming cleaning jobs for properties assigned to you. A Host’s linked reservation calendar appears automatically, so you don’t need to copy or manage their feed.</p></article>
      <article><h3>A clear checklist for each clean</h3><p>Regular and Deep Clean lists cover the details. For Host-assigned work, open the relevant saved job checklist with the property’s applicable tasks, rather than setting it up yourself.</p></article>
    </div></section>
    <section className="product-band"><div className="public-container acquisition-split" data-reveal><div><p className="eyebrow">From arrival to submission</p><h2>Everything needed<br />for the assigned work.</h2></div><div><p>Open the authorised property Start Guide when you need access instructions, equipment locations or lock-up guidance. The Host controls assignment; private property information is available only while you’re authorised.</p><p>If something needs attention during the clean, report an issue against the job. When the checklist is complete, add 3–6 completion photos, review the evidence and submit it for Host review.</p><p>You and the Host work through Turnli without a public Cleaner directory or unnecessary sharing of personal contact details.</p><a className="public-text-link" href="/software/airbnb-cleaning">Explore the shared cleaning workflow <span aria-hidden="true">↗</span></a><p className="related-link">Also manage a holiday let? <a href="/airbnb-cleaning">See Turnli for Hosts.</a></p></div></div></section>
    <section className="final-cta" aria-labelledby="join-title"><div className="public-container"><p className="eyebrow">Your customers. Your workspace.</p><h2 id="join-title">Make room for<br />a more organised day.</h2><p>Create your own login. Bring your existing work, or accept a Host’s invitation.</p><div className="public-actions"><a className="public-button" href="/register">Join Turnli free <span aria-hidden="true">↗</span></a></div></div></section>
  </AcquisitionPage>;
}
