import AcquisitionPage from '../../../features/marketing/AcquisitionPage';
import { publicMetadata, publicPages } from '../../../features/marketing/metadata';
import '../../../features/marketing/local.css';

export const metadata = publicMetadata(publicPages[6]);
export default function Page() {
  return <AcquisitionPage page={publicPages[6]} parent={publicPages[1]}>
    <section className="public-container acquisition-hero" aria-labelledby="london-title">
      <div className="hero-copy"><p className="eyebrow">For London Airbnb & short-term rental Hosts</p><h1 id="london-title">Airbnb cleaning in London, <em>with every property accounted for.</em></h1>
        <p className="public-lead">From an apartment to a family house or serviced accommodation, the cleaning brief should fit the property. Get a fixed price, then organise the access, linen and handover with the Cleaner doing the work.</p>
        <div className="public-actions"><a className="public-button" href="/quote" aria-describedby="price-next-step">Get your cleaning price <span aria-hidden="true">↗</span></a><a className="public-text-link" href="#your-cleaner">Already have a Cleaner?</a></div>
        <p id="price-next-step" className="local-conversion-note">Calculate your price without registering. An account is only needed when you choose to save and continue.</p>
      </div>
      <aside className="acquisition-note local-intro" aria-labelledby="london-start"><p className="eyebrow">One property or several</p><h2 id="london-start">A cleaning window<br />is only part of the plan.</h2><p>Allow for the journey, building entry and linen handover as well as cleaning. Two properties with the same checkout time are not automatically two jobs that one Cleaner can cover.</p><p>London Cleaner availability through Turnli is developing. Seeing a quote does not reserve a Cleaner or guarantee coverage at your address.</p></aside>
    </section>

    <section className="product-band"><div className="public-container acquisition-split" data-reveal><div><p className="eyebrow">The London working day</p><h2>Plan the space<br />between the cleans.</h2><p className="section-lead">For a Host managing several London properties, a useful schedule includes how the Cleaner gets between them and into each building. Confirm the plan with your Cleaner; Turnli does not optimise travel routes or promise arrival times.</p></div><div className="local-context">
      <h3>Allow a real journey between properties</h3><p>Check the addresses and travel arrangements before agreeing consecutive jobs. If travelling by public transport, use <a className="public-text-link" href="https://tfl.gov.uk/plan-a-journey/">TfL’s journey planner</a> for the intended day and time. Carrying supplies or linen may also affect what is practical; a shared postcode area is not a travel-time estimate.</p>
      <h3>Separate arrival from building access</h3><p>For apartments or serviced accommodation, record reception handover arrangements, the correct entrance, floor and lift access. For houses, distinguish the guest entrance from any separate service access. Check parking or loading arrangements with the property or building contact before carrying equipment in.</p>
      <h3>Keep linen with the right property</h3><p>Label clean sets by property and bed size, identify where used linen should go and agree who moves it. If several homes turn over on the same day, confirm that each has the right spares; supplies being included does not make stock interchangeable between properties.</p>
      <h3>Check overlapping windows</h3><p>Compare the cleaning work with the gap before the next planned check-in. Agree changes directly if a guest leaves late. A scheduled checkout creates a planning point, not proof that the home is empty or that a Cleaner can enter.</p>
    </div></div></section>

    <section id="reference-prices" className="public-container public-section acquisition-section" aria-labelledby="prices-title" data-reveal>
      <p className="eyebrow">Different homes. A clear basis for price.</p><h2 id="prices-title">A fixed price<br />for the details you give.</h2><p className="section-lead">Use the same Turnli calculator for a London flat, a larger house or another short-term rental. Floor area, bathrooms and beds help describe the work; the starting price is not a flat rate for every property.</p>
      <div className="acquisition-grid local-prices"><article><h3>Regular Airbnb cleaning</h3><p className="local-price">From <strong>£60</strong></p><p>Routine turnovers using the 38-task Regular Clean standard.</p></article><article><h3>Deep cleaning</h3><p className="local-price">From <strong>£130</strong></p><p>More detailed cleaning using the 109-task Deep Clean standard.</p></article></div>
      <div className="local-brief"><h3>One quote flow, no borough price lists</h3><p>Enter the location, bedrooms, beds, bathrooms and size in m² or ft² if known. Unknown size is supported, and cleaning frequency does not change the current price. Cleaning supplies and normal linen/towel wash and dry are included.</p><p>Your fixed price is based on accurate property details; materially incomplete or inaccurate details may require recalculation. <a className="public-text-link" href="/quote">See your property’s Regular or Deep price</a> without creating an account. A quote does not book cleaning services or confirm a Cleaner’s availability.</p></div>
    </section>

    <section className="public-container public-section acquisition-section" aria-labelledby="property-work-title" data-reveal><p className="eyebrow">Keep the work attached to the home</p><h2 id="property-work-title">The right instructions.<br />The right job.</h2><div className="acquisition-grid">
      <article><h3>Keep properties distinct</h3><p>Link each property’s reservation calendar and assign its Cleaner. Eligible reservation turnovers become planned cleaning jobs. Each job has its own checklist, with property-specific not-applicable tasks excluded.</p></article>
      <article><h3>Share operational details securely</h3><p>The assigned Cleaner gets the authorised calendar and a read-only Start Guide for that property. Keep building entry, equipment and lock-up instructions there, away from public pages and cleaning task lists.</p></article>
      <article><h3>Review each completed clean</h3><p>Issues can be reported against the job. After the checklist and 3–6 completion photos are submitted, the Host reviews the evidence and approves the clean or reports an issue.</p></article>
    </div><a className="public-text-link" href="/#operations">Explore the standard cleaning checklists <span aria-hidden="true">↗</span></a></section>

    <section id="your-cleaner" className="product-band"><div className="public-container acquisition-split" data-reveal><div><p className="eyebrow">Keep the people who know your properties</p><h2>Already have<br />a Cleaner?</h2></div><div><p>Invite your existing Cleaner to Turnli instead of starting a new search. With a Host workspace, you can manage their property assignment, upcoming work and cleaning instructions together.</p><p>Your Cleaner uses their own login and sees only the Host property information they are authorised to use. You retain control of the Host’s calendars and property setup.</p><a className="public-text-link" href="/register">Invite your existing Cleaner to Turnli <span aria-hidden="true">↗</span></a><p className="local-conversion-note">Create an account to start. Host workspace access is required for property invitations.</p><a className="public-text-link" href="/software/airbnb-cleaning">Explore software for managing multiple properties</a></div></div></section>

    <section className="public-container public-section acquisition-section" aria-labelledby="cleaners-title" data-reveal><p className="eyebrow">For independent Cleaners & cleaning businesses</p><h2 id="cleaners-title">Clean Airbnbs in London.</h2><p className="section-lead">Join Turnli free to manage your existing short-term-rental customers and cleaning schedules. Keep customer properties and Host-assigned work together without mixing up their instructions.</p><p className="section-lead">As local Host demand and marketplace availability develop, Turnli is building new cleaning opportunities. There are no guaranteed jobs, borough coverage or earnings from joining.</p><a className="public-text-link" href="/cleaners/airbnb-cleaning-jobs/">Explore Turnli for Cleaners <span aria-hidden="true">↗</span></a></section>

    <section className="public-container public-section acquisition-section" aria-labelledby="questions-title"><h2 id="questions-title">Before you line up the next jobs.</h2><div className="local-questions">
      <details><summary>Can the same Cleaner cover two properties on one day?</summary><p>Agree this with the Cleaner using the work involved, access windows and journey between properties. Turnli keeps the jobs organised but does not calculate travel routes or guarantee that overlapping turnovers are feasible.</p></details>
      <details><summary>Does the quote confirm that a Cleaner covers my borough?</summary><p>No. The price describes the cleaning requirement, not current local availability. Turnli’s marketplace is developing; you can already bring an existing Cleaner and manage your relationship through a Host workspace.</p></details>
      <details><summary>Where should reception and key-handover instructions go?</summary><p>Put property-specific access and lock-up guidance in the secure Start Guide. Keep it current when the building’s arrangements change. It should not appear in the public quote, a public listing or the Regular/Deep cleaning task list.</p></details>
    </div></section>
    <section className="final-cta" aria-labelledby="final-title"><div className="public-container"><p className="eyebrow">Your London property, clearly priced</p><h2 id="final-title">Start with one home.<br />Know the cleaning price.</h2><p>Get your fixed price first. Create an account only when you choose to save and continue.</p><div className="public-actions"><a className="public-button" href="/quote">Get your cleaning price <span aria-hidden="true">↗</span></a></div><a className="local-national-link" href="/airbnb-cleaning">Explore Airbnb cleaning with Turnli</a></div></section>
  </AcquisitionPage>;
}
